image: node:latest

cache:
  key: "$CI_PROJECT_ID"
  paths:
  - node_modules/

stages:
- build
- deploy
- restart

building:
  stage: build
  variables:
    NODE_ENV: "production"
  script:
  - npm i --no-optional
  - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
    - .nuxt => universal
  only:
  - master

deploy-app:
  stage: deploy
  only:
  - master
  script:
  - mkdir -p /opt/app/myongoingscalendar-frontend/.nuxt
  - cp -R ./universal/* /opt/app/myongoingscalendar-frontend/.nuxt
  - cp -R ./static/* /opt/app/myongoingscalendar-frontend/static
  - cp -f ./nuxt.config.js /opt/app/myongoingscalendar-frontend/
  - cp -f ./package.json /opt/app/myongoingscalendar-frontend/
  - cd /opt/app/myongoingscalendar-frontend/
  - npm i
  tags:
  - shell

deploy-helpers:
  stage: deploy
  only:
  - master
  script:
  - mkdir -p /opt/app/helpers
  - cp -f ./vibrant.js /opt/app/helpers
  - cp -f ./webp.js /opt/app/helpers
  - cd /opt/app/helpers
  - npm i express
  - npm i node-vibrant
  - npm i webp-converter
  tags:
  - shell

deploy-pm2-config:
  stage: deploy
  only:
  - master
  script:
  - cp -f ./ecosystem.config.js /opt/app
  - npm i pm2 -g
  tags:
  - shell

restart:
  stage: restart
  only:
  - master
  script:
  - pm2 restart ecosystem.config.js
  tags:
  - shell
