image: node:latest

cache:
  key: "$CI_PROJECT_ID"
  paths:
  - node_modules/

variables:
  APP_PATH: /opt/app
  FRONT_PATH: ${APP_PATH}/myongoingscalendar-frontend
  HELPERS_PATH: ${APP_PATH}/helpers

stages:
- build
- deploy
- restart

building:
  stage: build
  variables:
    NODE_ENV: "production"
  script:
  - npm i --no-optional
  - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
    - .nuxt
  only:
  - master

deploy-app:
  stage: deploy
  only:
  - master
  script:
  - mkdir -p ${FRONT_PATH}/.nuxt
  - rsync -cavu --delete ./.nuxt/ ${FRONT_PATH}/.nuxt
  - rsync -cavu --delete ./static/ ${FRONT_PATH}/static
  - cp -f ./{nuxt.config.js,package.json} ${FRONT_PATH}
  - cd ${FRONT_PATH}
  - npm i
  tags:
  - shell

deploy-helpers:
  stage: deploy
  only:
  - master
  script:
  - mkdir -p ${HELPERS_PATH}
  - cp -f ./{vibrant.js,webp.js} ${HELPERS_PATH}
  - cd ${HELPERS_PATH}
  - npm i express node-vibrant webp-converter
  tags:
  - shell

deploy-pm2-config:
  stage: deploy
  only:
  - master
  script:
  - cp -f ./ecosystem.config.js ${APP_PATH}
  - npm i pm2 -g
  tags:
  - shell

restart:
  stage: restart
  only:
  - master
  script:
  - pm2 restart ecosystem.config.js
  - pm2 startup
  - pm2 save
  tags:
  - shell
