cache:
  key: "$CI_PROJECT_ID"
  paths:
  - node_modules/

stages:
- build
- deploy

building:
  stage: build
  variables:
    NODE_ENV: "production"
  script:
  - npm i --no-optional
  - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
    - .nuxt/dist
  only:
  - master

deploy:
  stage: deploy
  only:
  - master
  script:
  - cp -R ./.nuxt/dist/* /opt/app/dist/
  - npm i -g pm2
  - pm2 deploy ecosystem.config.js production
  tags:
  - shell
