import Vue from 'vue'
import Vuetify, {
    VAlert,
    VApp,
    VAutocomplete,
    VAvatar,
    VBtn,
    VCard,
    VCheckbox,
    VChip,
    VDataTable,
    VDialog,
    VDivider,
    VExpansionPanel,
    VFooter,
    VForm,
    VIcon,
    VImg,
    VList,
    VListTile,
    VListTileAction,
    VListTileContent,
    VListTileTitle,
    VMenu,
    VNavigationDrawer,
    VPagination,
    VProgressCircular,
    VRating,
    VSelect,
    VSnackbar,
    VSubheader,
    VSwitch,
    VTab,
    VTabs,
    VTextField,
    VTextarea,
    VToolbar,
    VTooltip
} from 'vuetify/lib'

Vue.use(Vuetify, {
    components: {
        VAlert,
        VApp,
        VAutocomplete,
        VAvatar,
        VBtn,
        VCard,
        VCheckbox,
        VChip,
        VDataTable,
        VDialog,
        VDivider,
        VExpansionPanel,
        VFooter,
        VForm,
        VIcon,
        VImg,
        VList,
        VListTile,
        VListTileAction,
        VListTileContent,
        VListTileTitle,
        VMenu,
        VNavigationDrawer,
        VPagination,
        VProgressCircular,
        VRating,
        VSelect,
        VSnackbar,
        VSubheader,
        VSwitch,
        VTab,
        VTabs,
        VTextField,
        VTextarea,
        VToolbar,
        VTooltip
    },
    options: {
        minifyTheme: function (css) {
            return process.env.NODE_ENV === 'production'
                ? css.replace(/[\s|\r\n|\r|\n]/g, '')
                : css
        }
    }
});
